### ISSUE TITLE
We are getting connection closed error while trying to generating the PDF merge by Adobe.DocumentCloud.Services

### ISSUE THREAD

**Issue by sivarajanr22** [AdobeDocs/adobe-dev-console#29]
### Expected Behaviour
We are looking for 

### Actual Behaviour
1. The underlying connection was closed: An unexpected error occurred on a send
PS E:\exe\ErrorDrillDown\adobe_test\adobe_test> .\ConsoleAppTest.exe
Enter any key to start
Start of Process
Getting file names
Getting credentials
proceeding to executionContext
proceeding to createPdfOperation
Assigning doc file to file reference
Setting input
Starting to execute pdf operation
Error response received for the request: The underlying connection was closed: An unexpected error occurred on a send.
at Adobe.DocumentCloud.Services.core.http.HttpClient.ExecuteRequest[T](HttpBaseRequest baseRequest)
at Adobe.DocumentCloud.Services.core.http.HttpClient.<>c__DisplayClass11_0`1.<Execute>b__0()
at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates s
houldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepD
urationsEnumerable, Func`4 sleepDurationProvider)
at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
at Polly.Policy`1.Execute(Func`1 action)
at Adobe.DocumentCloud.Services.core.http.HttpClient.Execute[T](HttpBaseRequest baseRequest)
at Adobe.DocumentCloud.Services.core.api.CPFApi.CPFPredictApi[T](InternalExecutionContext context, ContentAnalyzerRequestsDto contentAnalyzer
RequestsDto, List`1 sourceFileRefList)
at Adobe.DocumentCloud.Services.core.api.CreatePDFApi.ConvertToPdf(InternalExecutionContext context, FileRefImpl sourceFileRef, CreatePDFOpti
ons createPdfOptions)
at Adobe.DocumentCloud.Services.pdfops.CreatePDFOperation.Execute(ExecutionContext context)
at ConsoleAppTest.Program.Main(String[] args) in C:\Users\61380\source\repos\ConsoleAppTest\ConsoleAppTest\Program.cs:line 76
Adobe.DocumentCloud.Services

2.  We tried to use the adobe login and got error

Error response received for the request: The SSL connection could not be established, see inner exception. Unable to read data from the transpor
t connection: An existing connection was forcibly closed by the remote host..

PS E:\exe\ErrorDrillDown\adobe_core_test_09032022_1\adobe_core_test> .\Adobe_core.exe
Enter any key to start
Start of Process
Getting file names
Getting credentials
proceeding to executionContext
proceeding to createPdfOperation
Assigning doc file to file reference
Setting input
Starting to execute pdf operation
Error response received for the request: The SSL connection could not be established, see inner exception. Unable to read data from the transpor
t connection: An existing connection was forcibly closed by the remote host..
at Adobe.DocumentCloud.Services.core.http.HttpClient.ExecuteRequest[T](HttpBaseRequest baseRequest)
at Adobe.DocumentCloud.Services.core.http.HttpClient.<>c__DisplayClass11_0`1.<Execute>b__0()
at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates s
houldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepD
urationsEnumerable, Func`4 sleepDurationProvider)
at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
at Polly.Policy`1.Execute(Func`1 action)
at Adobe.DocumentCloud.Services.core.http.HttpClient.Execute[T](HttpBaseRequest baseRequest)
at Adobe.DocumentCloud.Services.core.api.CPFApi.CPFPredictApi[T](InternalExecutionContext context, ContentAnalyzerRequestsDto contentAnalyzer
RequestsDto, List`1 sourceFileRefList)
at Adobe.DocumentCloud.Services.core.api.CreatePDFApi.ConvertToPdf(InternalExecutionContext context, FileRefImpl sourceFileRef, CreatePDFOpti
ons createPdfOptions)
at Adobe.DocumentCloud.Services.pdfops.CreatePDFOperation.Execute(ExecutionContext context)
at Adobe_core.Program.Main(String[] args) in C:\Users\61380\source\repos\Adobe_core\Adobe_core\Program.cs:line 79
Adobe.DocumentCloud.Services

### Reproduce Scenario (including but not limited to)
      We are trying to merge PDF which is not happening. we are getting connection closed error. It is working in local but not working in the server.
#### Steps to Reproduce
      
![error](https://user-images.githubusercontent.com/101244865/157393551-cb089db2-5c32-40aa-8cc7-353450c05385.JPG)
![error1](https://user-images.githubusercontent.com/101244865/157393647-95af9a70-5a17-4ab2-ac52-19ab19502098.JPG)

#### Platform and Version
    .Net windows service
#### Sample Code that illustrates the problem
  string StartService = ConfigurationManager.AppSettings["AdobeStartService"];
if (StartService == "true")
{
string privatekey = File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "/private.key"); //changes made by Nallasivan/Rahul/Chandana/uncommented the adobe service
string jsoncredentials = File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "/pdfservices-api-credentials.json");
PrivateKey jsoncred = JsonConvert.DeserializeObject<PrivateKey>(jsoncredentials);
Credentials credentials = Credentials.ServiceAccountCredentialsBuilder()
.WithAccountId(jsoncred.account_id)
.WithClientId(jsoncred.client_id)
.WithClientSecret(jsoncred.client_secret)
.WithOrganizationId(jsoncred.organization_id)
.WithPrivateKey(privatekey).Build();
ExecutionContext executionContext = ExecutionContext.Create(credentials);
CreatePDFOperation createPdfOperation = CreatePDFOperation.CreateNew();
// Set operation input from a source file.
FileRef source = FileRef.CreateFromLocalFile(docPath);
createPdfOperation.SetInput(source);
// Execute the operation.
FileRef result = createPdfOperation.Execute(executionContext);
// Save the result to the specified location.
result.SaveAs(DestinationPDFFilePath);
/* PDF conversion Ends */
}
#### Logs taken while reproducing problem
      Attached in the ticket

**Comment by sivarajanr22** [comment]
We checked firewall and TLs version. Then network team has changed setting and we are able to connect to the Adobe.DocumentCloud.Services , we are closing the ticket
